# Generated by Django 2.2.11 on 2020-03-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='useless',
        ),
    ]
